`#-------------------------------------------------
#
# Project created by QtCreator 2016-03-03T22:40:04
#
#-------------------------------------------------

# old qmake
# qmake.exe I:\Projects\KSU2016\01_Source\01_Qt\SapKsuSurgut\SapKsuSurgut.pro -r -spec win32-g++ "CONFIG+=debug"
#

QT       += core gui widgets network serialport xml script scripttools sql qml printsupport quick quickcontrols2
CONFIG   += c++11 precompile_header

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TARGET = SapKsuSurgut
TEMPLATE = app

# Use Precompiled headers (PCH)
PRECOMPILED_HEADER  = Common/PrefixHeader.h


SOURCES += main.cpp \
    Authentication/LoginDialog_copy.cpp \
    Authentication/SystemUser_copy.cpp \
    IOServer/nsNode/INode.cpp \
    IOServer/nsConnection/IConnection.cpp \
    IOServer/nsVariable/IVariable.cpp \
    IOServer/nsConnection/SerialPortConnection.cpp \
    IOServer/nsConnection/TcpConnection.cpp \
    IOServer/nsVariable/ModbusVariable.cpp \
    MainEngine.cpp \
    ModbusCrc.cpp \
    IOServer/nsTask/TaskManager.cpp \
    IOServer/nsTask/IDataTask.cpp \
    IOServer/nsNode/ModbusTcpNode.cpp \
    IOServer/nsNode/ModbusRtuNode.cpp \
    AppSettings/AppSettings.cpp \
    IOServer/IOServer.cpp \
    Logger/FileLogger.cpp \
    Logger/ILogger.cpp \
    Logger/LoggerTaskManager.cpp \
    Logger/LoggerWidget.cpp \
    Logger/WindowsEventLogger.cpp \
    Common/ThreadWorkingTemplates.cpp \
    Common/CommonEnums.cpp \
    IOServer/nsNode/ModbusNode.cpp \
    Ksu735Crc.cpp \
    IOServer/nsVariable/Ksu735Variable.cpp \
    Devices/DirectLogic/DirectLogicWidget.cpp \
    Devices/Device.cpp \
    Devices/DeviceDelegate.cpp \
    Devices/DeviceModel.cpp \
    Devices/Voltmeter/VoltmeterWidget.cpp \
    Devices/AFC/AFCWidget.cpp \
    Devices/MKTN/MKTNWidget.cpp \
    IOServerUI/IOWidgetsFactory.cpp \
    IOServerUI/Connection/SerialPortConnectionUI.cpp \
    IOServerUI/Connection/TcpConnectionUI.cpp \
    IOServerUI/IOWidget.cpp \
    IOServerUI/DomItem.cpp \
    IOServerUI/DomModel.cpp \
    IOServerUI/VariablesModel.cpp \
    IOServerUI/Node/ModbusNodeUI.cpp \
    IOServerUI/Variable/Ksu735VariableUI.cpp \
    IOServerUI/Variable/ModbusVariableUI.cpp \
    IOServer/nsVariable/VariableValue/DeviceVariableValue/DeviceVariableValueBase.cpp \
    IOServer/nsVariable/VariableValue/DeviceVariableValue/ModbusDeviceVariableValue.cpp \
    IOServer/nsVariable/VariableValue/DeviceVariableValue/Ksu735DeviceVariableValue.cpp \
    IOServer/nsVariable/VariableValue/VariableValueStrategy/VariableValueStrategy.cpp \
    IOServer/nsVariable/VariableValue/VariableValueStrategy/BitsetVariableValueStrategy.cpp \
    IOServer/nsVariable/VariableValue/VariableValueStrategy/NumberVariableValueStrategy.cpp \
    IOServer/nsVariable/VariableValue/VariableValueStrategy/EnumVariableValueStrategy.cpp \
    IOServer/nsVariable/VariableValue/VariableValueStrategy/RegisterVariableValueStrategy.cpp \
    DBConfig/DBConfig.cpp \
    Common/PushButtonPlus.cpp \
    DatabaseDirectory/CommunicationProtocols/CommunicationProtocol.cpp \
    DatabaseDirectory/CommunicationProtocols/ProtocolDialogMapper.cpp \
    Common/FKComboBoxDelegate/FKComboBoxDelegate.cpp \
    IOServerUI/Variable/LinearCoefficientsCalculationWidget.cpp \
    DatabaseDirectory/Classifier.cpp \
    DatabaseDirectory/InputDialogMapperInterface.cpp \
    DatabaseDirectory/HexConvertDelegate.cpp \
    DatabaseDirectory/KsuTypes/KsuTypes.cpp \
    DatabaseDirectory/KsuTypes/KsuTypesDialogMapper.cpp \
    DatabaseDirectory/ParametrAliases/ParametrAliases.cpp \
    DatabaseDirectory/ParametrAliases/ParametrAliasesDialogMapper.cpp \
    DatabaseDirectory/ParametrTemplates/ParametrTemplates.cpp \
    DatabaseDirectory/ParametrTemplates/ParametrTemplatesDialogMapper.cpp \
    DatabaseDirectory/KSU0x20Parametrs/KSU0x20Parametr.cpp \
    DatabaseDirectory/KSU0x20Parametrs/KSU0x20ParametrsDelegate.cpp \
    DatabaseDirectory/KSU0x20Parametrs/KSU0x20ParametrsFormatDelegate.cpp \
    DatabaseDirectory/KSU0x20Parametrs/KSU0x20ParametrsMap.cpp \
    DatabaseDirectory/KSU0x20Parametrs/KSU0x20ParametrsModel.cpp \
    DatabaseDirectory/KSU0x20Parametrs/KSU0x20ParametrsValueDelegate.cpp \
    DatabaseDirectory/KSUModbusParametrs/KSUModbusParametrsMap.cpp \
    DatabaseDirectory/KSUModbusParametrs/KSUModbusParametrsModel.cpp \
    Common/FKValidatorSpinBox/FKValidatorHelper.cpp \
    Common/FKValidatorSpinBox/FKInt64Validator.cpp \
    DatabaseDirectory/KSUModbusParametrs/ModbusVariableForm/ModbusVariableForm.cpp \
    DatabaseDirectory/KSUModbusParametrs/ModbusVariableForm/ModbusVariableEditBitsetValue.cpp \
    Common/FKProxyDelegate/FKProxyDelegate.cpp \
    DatabaseDirectory/KsuSoftwareVersions/KsuSoftwareVersions.cpp \
    DatabaseDirectory/KsuSoftwareVersions/KsuSoftwareVersionDialogMapper.cpp \
    StartWindow/StartDiagnosticWindow_copy.cpp \
    Stylesheets/QmlStyle.cpp \
    TestManager/ExecutorWindow/ExecutorWindow_copy.cpp \
    TestManager/JSTestStep.cpp \
    TestManager/ExecutorWindow/ITestStep.cpp \
    TestManager/ExecutorWindow/ITest.cpp \
    TestManager/JSTest.cpp \
    TestManager/ExecutorWindow/TestCreator.cpp \
    TestManager/CppTest.cpp \
    TestManager/CppTestStep.cpp \
    TestManager/ExecutorWindow/ExecutorWindow.cpp \
    TestManager/EditorWindow/EngineLocalVariable.cpp \
    TestManager/EditorWindow/EditorWindow.cpp \
    Scene/Items/ISceneItem.cpp \
    Scene/Items/SceneTextWidget.cpp \
    Scene/Items/SceneVariableWidget.cpp \
    Scene/EditableScene.cpp \
    Scene/EditableSceneWidget.cpp \
    Scene/Scene.cpp \
    Scene/SceneControlPanel.cpp \
    Scene/SceneItemListWidget.cpp \
    Scene/SceneView.cpp \
    Scene/SceneWidget.cpp \
    Common/ParametrAliases/ParameterAliasWidget.cpp \
    Common/ParametrAliases/ParameterAliasSelectWidget.cpp \
    Common/ParametrAliases/ParameterAliasSelectModel.cpp \
    Common/ParametrAliases/ParameterAliasWidgetDelegate.cpp \
    IOServer/nsNode/Ksu735Node.cpp \
    IOServer/nsConnection/KsuSerialPortConnection.cpp \
    IOServer/EnergoForm/EnergoFormVariable.cpp \
    IOServer/EnergoMonitor/EnergoMonitorNode.cpp \
    EnergoFormCrc16.cpp \
    IOServer/EnergoForm/EnergoFormWordVariable.cpp \
    IOServer/EnergoForm/EnergoFormDWordVariable.cpp \
    IOServer/EnergoForm/EnergoFormNode.cpp \
    Devices/EnergoFormDevice/EnergoFormDeviceWidget.cpp \
    Common/FKValidatorSpinBox/FKUInt64Validator.cpp \
    IOServerUI/IVariableDelegate/IVariableDelegate.cpp \
    IOServer/NodeError/NodeError.cpp \
    ManualTesting/Ksu735/Manual0x10Testing/Ksu735Manual0x10TestingModel.cpp \
    ManualTesting/Ksu735/Manual0x10Testing/Ksu735Manual0x10TestingWidget.cpp \
    ManualTesting/KsuManualTestingWidget.cpp \
    ManualTesting/Ksu735/Manual0x20Testing/Ksu735Manual0x20TestingWidget.cpp \
    ManualTesting/Ksu735/Manual0x20Testing/Ksu735Manual0x20TestingModel.cpp \
    ManualTesting/Ksu735/Manual0x20Testing/Ksu735Manual0x20TestingVariableDelegate.cpp \
    ManualTesting/Ksu735/Manual0x20Testing/Ksu735Manual0x20TestingValueDelegate.cpp \
    StartWindow/StartWindow.cpp \
    DatabaseDirectory/SAPParametrs/SAPParametrs.cpp \
    DatabaseDirectory/SAPParametrs/SAPParametrsDialogMapper.cpp \
    DatabaseDirectory/Users/Users.cpp \
    DatabaseDirectory/Users/UsersDialogMapper.cpp \
    Authentication/LoginDialog.cpp \
    Authentication/SystemUser.cpp \
    StartWindow/ActionStyledWidget.cpp \
    StartWindow/ActionStyledFlowLayout.cpp \
    StartWindow/StartDiagnosticWindow.cpp \
    ManualTesting/Ksu735/ManualFullTesting/Ksu735ManualFullTestingWidget.cpp \
    Common/FKValidatorSpinBox/FKCP866StringValidator.cpp \
    ManualTesting/Ksu735/ManualFullTesting/Ksu735ManualFullTestingModel.cpp \
    ManualTesting/Common/ManualTestingConnectionParametrsWidget.cpp \
    SelectKsuWindow/SelectKsuWindow.cpp \
    KSUPortConnection/KSUPortConnectionWidget.cpp \
    StartWindow/ActionStyledGroupMenuWidget.cpp \
    StartWindow/ActionControlWidgetsShow.cpp \
    IOServer/EnergoMonitor/EnergoMonitorDeviceVariableValue/EnergoMonitor12Integer20FractionDeviceVariableValue.cpp \
    IOServer/EnergoMonitor/EnergoMonitorDeviceVariableValue/EnergoMonitorSigned3Integer12FractionDeviceVariableValue.cpp \
    IOServer/EnergoMonitor/EnergoMonitorDeviceVariableValue/EnergoMonitor16Signed32Integer16FractionDeviceVariableValue.cpp \
    IOServer/EnergoMonitor/EnergoMonitorVariable.cpp \
    IOServer/nsNode/ModbusKsuNode.cpp \
    Devices/NL/NLWidget.cpp \
    Devices/DevicesTabWidget.cpp \
    ManualTesting/Common/InterferenceSender.cpp \
    Devices/DevicesWindow.cpp \
    IOServer/nsNode/Ksu735NodeArchive.cpp \
    ManualTesting/Ksu735/Manual0x30Testing/Ksu735Manual0x30TestingWidget.cpp \
    ManualTesting/Ksu735/Manual0x30Testing/Ksu735Manual0x30TestingModel.cpp \
    ManualTesting/Ksu735/ManualFullTesting/Ksu735ManualFullTestingValueDelegate.cpp \
    DatabaseDirectory/KsuCommunicationProtocolClassifiers/ErrorCodes/ErrorCodes.cpp \
    DatabaseDirectory/KsuCommunicationProtocolClassifiers/ErrorCodes/ErrorCodesDialogMapper.cpp \
    DatabaseDirectory/KsuCommunicationProtocolClassifiers/KindOfLaunch/KindOfLaunch.cpp \
    DatabaseDirectory/KsuCommunicationProtocolClassifiers/KindOfLaunch/KindOfLaunchDialogMapper.cpp \
    DatabaseDirectory/KsuCommunicationProtocolClassifiers/ReturnFlags10/ReturnFlags10.cpp \
    DatabaseDirectory/KsuCommunicationProtocolClassifiers/ReturnFlags10/ReturnFlags10DialogMapper.cpp \
    DatabaseDirectory/KsuCommunicationProtocolClassifiers/StatusWordInterpretationCodes/StatusWordDialogMapper.cpp \
    DatabaseDirectory/KsuCommunicationProtocolClassifiers/StatusWordInterpretationCodes/StatusWordInterpretationCodes.cpp \
    DatabaseDirectory/KsuCommunicationProtocolClassifiers/WorkMode/WorkMode.cpp \
    DatabaseDirectory/KsuCommunicationProtocolClassifiers/WorkMode/WorkModeDialogMapper.cpp \
    DatabaseDirectory/KsuCommunicationProtocolClassifiers/StopReasonCodes/StopReasonCodes.cpp \
    DatabaseDirectory/KsuCommunicationProtocolClassifiers/StopReasonCodes/StopReasonCodesDialogMapper.cpp \
    TestManager/TestKitConfigureWindow/TestKitConfigureWindow.cpp \
    TestManager/TestKitConfigureWindow/TestKit.cpp \
    TestManager/TestKitConfigureWindow/TestKitDialogMapper.cpp \
    TestManager/TestKitConfigureWindow/TestKitTests.cpp \
    TestManager/TestKitConfigureWindow/Tests.cpp \
    TestManager/TestKitConfigureWindow/TestsDialogMapper.cpp \
    TestManager/TestCreatorControlWindow/TestCreatorControlWindow.cpp \
    StartWindow/StartWindowTesting.cpp \
    Common/QSyntaxHighlighter/XMLSyntaxHighlighter/XMLSyntaxHighlighter.cpp \
    Common/QSyntaxHighlighter/JSSyntaxHighlighter/JSSyntaxHighlighter.cpp \
    Common/QPlainTextEdit/CodeEditorPlainTextEdit/CodeEditorPlainTextEdit.cpp \
    Common/CommonTemplates.cpp \
    ManualTesting/ModbusKsu/ModbusKsuManualFullTesting/ModbusKsuManualFullTestingModel.cpp \
    ManualTesting/ModbusKsu/ModbusKsuManualFullTesting/ModbusKsuManualFullTestingWidget.cpp \
    StartWindow/ActionStyledBooleanWidget.cpp \
    ManualTesting/ModbusKsu/ModbusKsuManualSelectiveTesting/ModbusKsuManualSelectiveTestingWidget.cpp \
    ManualTesting/ModbusKsu/ModbusKsuManualSelectiveTesting/ModbusKsuManualSelectiveTestingModel.cpp \
    ManualTesting/ModbusKsu/ModbusKsuManualSelectiveTesting/ModbusKsuManualSelectiveTestingVariableDelegate.cpp \
    ManualTesting/ModbusKsu/ModbusKsuManualSelectiveTesting/ModbusVariableAddressSelectSpinBox.cpp \
    ManualTesting/ModbusKsu/ModbusKsuManualTestingValueDelegate.cpp \
    IOServer/nsNode/ModbusKsuArchive/ModbusKsuCurrentParametrsArchive.cpp \
    IOServer/nsNode/ModbusKsuArchive/ModbusKsuChangeParametrsArchive.cpp \
    TestManager/TestKitSelectWindow/TestKitSlectWindow.cpp \
    Common/QMessageBox/ScriptDelayMessageBox/ScriptDelayMessageBox.cpp \
    Devices/IcpCon/IcpConWidget.cpp \
    Devices/Circutor/CircutorWidget.cpp \
    Devices/IRZFC/IRZFCWidget.cpp \
    IOServer/nsNode/ModbusKsuArchive/ModbusKsuEventsArchive.cpp \
    IOServer/nsNode/ModbusKsuArchive/ModbusKsuLaunchParametrsArchive.cpp \
    ManualTesting/ModbusKsu/ModbusKsuManualTestingArchives/ModbusKsuManualTestingArchivesForm.cpp \
    IOServer/nsNode/ModbusKsuArchive/IModbusKsuArchive.cpp \
    ManualTesting/ModbusKsu/ModbusKsuManualTestingArchives/ModbusKsuManualTestingChangeParametrsArchiveWidget.cpp \
    ManualTesting/ModbusKsu/ModbusKsuManualTestingArchives/ModbusKsuManualTestingChangeParametrsArchiveModel.cpp \
    ManualTesting/ModbusKsu/ModbusKsuManualTestingArchives/ModbusKsuManualTestingCurrentParametrsArchiveModel.cpp \
    ManualTesting/ModbusKsu/ModbusKsuManualTestingArchives/ModbusKsuManualTestingCurrentParametrsArchiveWidget.cpp \
    ManualTesting/ModbusKsu/ModbusKsuManualTestingArchives/ModbusKsuManualTestingEventsArchiveModel.cpp \
    ManualTesting/ModbusKsu/ModbusKsuManualTestingArchives/ModbusKsuManualTestingEventsArchiveWidget.cpp \
    StartWindow/SwitchWidget.cpp \
    ManualTesting/ModbusKsu/ModbusKsuManualTestingArchives/ModbusKsuManualTestingLaunchParametrsArchiveModel.cpp \
    ManualTesting/ModbusKsu/ModbusKsuManualTestingArchives/ModbusKsuManualTestingLaunchParametrsArchiveWidget.cpp \
    DatabaseDirectory/CommunicationProtocolClassifiers.cpp \
    DatabaseDirectory/KsuCommunicationProtocolClassifiers/ModbusArchivesEventClasses/ModbusArchivesEventClasses.cpp \
    DatabaseDirectory/KsuCommunicationProtocolClassifiers/ModbusArchivesEventClasses/ModbusArchivesEventClassesDialogMapper.cpp \
    DatabaseDirectory/KsuCommunicationProtocolClassifiers/ModbusArchivesEventCodes/ModbusArchivesEventCodes.cpp \
    DatabaseDirectory/KsuCommunicationProtocolClassifiers/ModbusArchivesEventCodes/ModbusArchivesEventCodesDialogMapper.cpp \
    TestManager/ExecutorWindow/TestExternalVariableModel.cpp \
    TestManager/ExecutorWindow/TestExternalVariableWidget.cpp \
    TestManager/ExecutorWindow/TestInternalVariableWidget.cpp \
    TestManager/ExecutorWindow/TestIntenralVariableModel.cpp \
    TestManager/ExecutorWindow/TestInternalVariableDelegate.cpp \
    Devices/UPS/UPSWidget.cpp \
    Attestation/AnalogOutputWidget.cpp \
    Attestation/AttestationWindow.cpp \
    Attestation/AnalogInputWidget.cpp \
    Attestation/AnalogInputsContainerWidget.cpp \
    Attestation/AnalogOutputsContainerWidget.cpp \
    Attestation/DigitalOutputWidget.cpp \
    Attestation/DigitalOutputsContainerWidget.cpp \
    Attestation/DigitalInputWidget.cpp \
    Attestation/DigitalInputsContainerWidget.cpp \
    Attestation/PowerSupplyWidget.cpp \
    Attestation/AttestationEnergoform.cpp \
    Attestation/AnalogVoltageOutputWidget.cpp \
    Devices/EnergoFormDevice/EnergoFormRunningControl.cpp \
    DatabaseDirectory/TestHistoryReport/TestHistoryReport.cpp \
    TestManager/JSTestScriptEngine.cpp \
    ReportManager/ReportConfigure.cpp \
    ReportManager/OperatorClickReport.cpp \
    Common/DateRangePicker.cpp \
    Devices/NL/RizElecton08Widget.cpp \
    TestManager/ExecutorWindow/ExecutorSimpleWindow.cpp \
    ReportManager/ParamsReport.cpp \
    StartWindow/SystemTrayIcon.cpp \
    Logger/Logger2/LoggerTaskManager2.cpp \
    Logger/Logger2/ILogger2.cpp \
    Logger/Logger2/KsuLogger.cpp \
    Logger/Logger2/Logger2TableModel.cpp \
    Logger/KsuLogWidget/KsuLogWidget.cpp \
    SelectKsuWindow/KsuInfoWindow.cpp \
    SelectKsuWindow/KsuTestResultDialog.cpp \
    DatabaseDirectory/SUTypes/SUTypes.cpp \
    DatabaseDirectory/SUTypes/SUTypesDialogMapper.cpp \
    Common/QMessageBox/ScriptDelayMessageBox/ProgressBarMessageBox.cpp \
    TestManager/TestKitSelectWindow/TestKitSlectWindow_copy.cpp \
    UpdateKsuWizard/UpdateKsuWizard.cpp \
    UpdateKsuWizard/ClassReadBeforePage.cpp \
    ManualTesting/ModbusKsu/ModbusLinkTestingWidget/ModbusLinkTedtingWidget.cpp \
    ReportManager/FaultReport.cpp \
    ManualTesting/ModbusKsu/ModbusKsuPasswordsWidget/ModbusKsuPasswordsWidget.cpp \
    Common/SearchProxyModelWidget/SearchProxyModelWidget.cpp \
    Devices/IcpCon/IcpConMechWidget.cpp \
    IOServer/dataserver/dataserver.cpp \
    IOServer/dataserver/dataserver_p.cpp \
    IOServer/dataserver/devicevariable.cpp \
    IOServer/dataserver/devicevariable_p.cpp \
    Common/CustomizableTableView/CustomizableTableView.cpp \
    Attestation/AttestationMechosWidget.cpp \
    ErrorClassifier/ErrorClassifier.cpp

HEADERS  += Common/PrefixHeader.h \
    Authentication/LoginDialog_copy.h \
    Authentication/SystemUser_copy.h \
    IOServer/nsNode/INode.h \
    IOServer/nsConnection/IConnection.h \
    IOServer/nsVariable/IVariable.h \
    IOServer/nsConnection/SerialPortConnection.h \
    IOServer/nsConnection/TcpConnection.h \
    IOServer/nsVariable/ModbusVariable.h \
    MainEngine.h \
    ModbusCrc.h \
    IOServer/nsTask/TaskManager.h \
    IOServer/nsTask/IDataTask.h \
    IOServer/nsNode/ModbusTcpNode.h \
    IOServer/nsNode/ModbusRtuNode.h \
    AppSettings/AppSettings.h \
    IOServer/IOServer.h \
    Logger/FileLogger.h \
    Logger/ILogger.h \
    Logger/LoggerTaskManager.h \
    Logger/LoggerWidget.h \
    Logger/WindowsEventLogger.h \
    Common/PrefixHeader.h \
    Common/ThreadWorkingTemplates.h \
    Common/CommonEnums.h \
    IOServer/nsNode/ModbusNode.h \
    Ksu735Crc.h \
    IOServer/nsVariable/Ksu735Variable.h \
    Devices/DirectLogic/DirectLogicWidget.h \
    Devices/Device.h \
    Devices/DeviceDelegate.h \
    Devices/DeviceModel.h \
    Devices/Voltmeter/VoltmeterWidget.h \
    Devices/AFC/AFCWidget.h \
    Devices/MKTN/MKTNWidget.h \
    IOServerUI/IOWidgetsFactory.h \
    IOServerUI/Connection/SerialPortConnectionUI.h \
    IOServerUI/Connection/TcpConnectionUI.h \
    IOServerUI/IOWidget.h \
    IOServerUI/DomItem.h \
    IOServerUI/DomModel.h \
    IOServerUI/VariablesModel.h \
    IOServerUI/Node/ModbusNodeUI.h \
    IOServerUI/Variable/Ksu735VariableUI.h \
    IOServerUI/Variable/ModbusVariableUI.h \
    Common/CommonTemplates.h \
    IOServer/nsVariable/VariableValue/DeviceVariableValue/IDeviceVariableValue.h \
    IOServer/nsVariable/VariableValue/DeviceVariableValue/DeviceVariableValueBase.h \
    IOServer/nsVariable/VariableValue/DeviceVariableValue/ModbusDeviceVariableValue.h \
    IOServer/nsVariable/VariableValue/DeviceVariableValue/Ksu735DeviceVariableValue.h \
    IOServer/nsVariable/VariableValue/VariableValueTypeTraits.h \
    IOServer/nsVariable/VariableValue/ServerVariableValue.h \
    IOServer/nsVariable/VariableValue/VariableValueStrategy/VariableValueStrategy.h \
    IOServer/nsVariable/VariableValue/VariableValueStrategy/BitsetVariableValueStrategy.h \
    IOServer/nsVariable/VariableValue/VariableValueStrategy/NumberVariableValueStrategy.h \
    IOServer/nsVariable/VariableValue/VariableValueStrategy/EnumVariableValueStrategy.h \
    IOServer/nsVariable/VariableValue/VariableValueStrategy/RegisterVariableValueStrategy.h \
    DBConfig/DBConfig.h \
    Common/PushButtonPlus.h \
    DatabaseDirectory/CommunicationProtocols/CommunicationProtocol.h \
    DatabaseDirectory/CommunicationProtocols/ProtocolDialogMapper.h \
    Common/FKComboBoxDelegate/FKComboBoxDelegate.h \
    IOServerUI/Variable/LinearCoefficientsCalculationWidget.h \
    DatabaseDirectory/Classifier.h \
    DatabaseDirectory/InputDialogMapperInterface.h \
    DatabaseDirectory/HexConvertDelegate.h \
    DatabaseDirectory/KsuTypes/KsuTypes.h \
    DatabaseDirectory/KsuTypes/KsuTypesDialogMapper.h \
    DatabaseDirectory/ParametrAliases/ParametrAliases.h \
    DatabaseDirectory/ParametrAliases/ParametrAliasesDialogMapper.h \
    DatabaseDirectory/ParametrTemplates/ParametrTemplates.h \
    DatabaseDirectory/ParametrTemplates/ParametrTemplatesDialogMapper.h \
    DatabaseDirectory/KSU0x20Parametrs/KSU0x20Parametr.h \
    DatabaseDirectory/KSU0x20Parametrs/KSU0x20ParametrsDelegate.h \
    DatabaseDirectory/KSU0x20Parametrs/KSU0x20ParametrsFormatDelegate.h \
    DatabaseDirectory/KSU0x20Parametrs/KSU0x20ParametrsMap.h \
    DatabaseDirectory/KSU0x20Parametrs/KSU0x20ParametrsModel.h \
    DatabaseDirectory/KSU0x20Parametrs/KSU0x20ParametrsValueDelegate.h \
    DatabaseDirectory/KSUModbusParametrs/KSUModbusParametrsMap.h \
    DatabaseDirectory/KSUModbusParametrs/KSUModbusParametrsModel.h \
    DatabaseDirectory/KSUModbusParametrs/KSUModbusParamertDomItem.h \
    Common/FKValidatorSpinBox/FKValidatorHelper.h \
    Common/FKValidatorSpinBox/FKInt64Validator.h \
    DatabaseDirectory/KSUModbusParametrs/ModbusVariableForm/ModbusVariableForm.h \
    DatabaseDirectory/KSUModbusParametrs/ModbusVariableForm/ModbusVariableEditBitsetValue.h \
    Common/FKProxyDelegate/FKProxyDelegate.h \
    DatabaseDirectory/KsuSoftwareVersions/KsuSoftwareVersions.h \
    DatabaseDirectory/KsuSoftwareVersions/KsuSoftwareVersionDialogMapper.h \
    StartWindow/StartDiagnosticWindow_copy.h \
    Stylesheets/QmlStyle.h \
    TestManager/ExecutorWindow/ExecutorWindow_copy.h \
    TestManager/JSTestStep.h \
    TestManager/ExecutorWindow/ITestStep.h \
    TestManager/ExecutorWindow/ITest.h \
    TestManager/JSTest.h \
    TestManager/ExecutorWindow/TestCreator.h \
    TestManager/CppTest.h \
    TestManager/CppTestStep.h \
    TestManager/ExecutorWindow/ExecutorWindow.h \
    TestManager/EditorWindow/EngineLocalVariable.h \
    TestManager/EditorWindow/EditorWindow.h \
    Scene/Items/ISceneItem.h \
    Scene/Items/SceneTextWidget.h \
    Scene/Items/SceneVariableWidget.h \
    Scene/EditableScene.h \
    Scene/EditableSceneWidget.h \
    Scene/Scene.h \
    Scene/SceneControlPanel.h \
    Scene/SceneItemListWidget.h \
    Scene/SceneView.h \
    Scene/SceneWidget.h \
    Common/ParametrAliases/ParameterAliasWidget.h \
    Common/ParametrAliases/ParameterAliasSelectWidget.h \
    Common/ParametrAliases/ParameterAliasSelectModel.h \
    Common/ParametrAliases/ParameterAliasWidgetDelegate.h \
    IOServer/nsNode/Ksu735Node.h \
    IOServer/nsConnection/KsuSerialPortConnection.h \
    IOServer/EnergoForm/EnergoFormVariable.h \
    IOServer/EnergoMonitor/EnergoMonitorNode.h \
    EnergoFormCrc16.h \
    IOServer/EnergoForm/EnergoFormWordVariable.h \
    IOServer/EnergoForm/EnergoFormDWordVariable.h \
    IOServer/EnergoForm/EnergoFormNode.h \
    Devices/EnergoFormDevice/EnergoFormDeviceWidget.h \
    Common/FKValidatorSpinBox/FKUInt64Validator.h \
    IOServerUI/IVariableDelegate/IVariableDelegate.h \
    IOServer/NodeError/NodeError.h \
    ManualTesting/Ksu735/Manual0x10Testing/Ksu735Manual0x10TestingModel.h \
    ManualTesting/Ksu735/Manual0x10Testing/Ksu735Manual0x10TestingWidget.h \
    ManualTesting/KsuManualTestingWidget.h \
    ManualTesting/Ksu735/Manual0x20Testing/Ksu735Manual0x20TestingWidget.h \
    ManualTesting/Ksu735/Manual0x20Testing/Ksu735Manual0x20TestingModel.h \
    ManualTesting/Ksu735/Manual0x20Testing/Ksu735Manual0x20TestingParametr.h \
    ManualTesting/Ksu735/Manual0x20Testing/Ksu735Manual0x20TestingVariableDelegate.h \
    ManualTesting/Ksu735/Manual0x20Testing/Ksu735Manual0x20TestingValueDelegate.h \
    StartWindow/StartWindow.h \
    DatabaseDirectory/SAPParametrs/SAPParametrs.h \
    DatabaseDirectory/SAPParametrs/SAPParametrsDialogMapper.h \
    DatabaseDirectory/Users/Users.h \
    DatabaseDirectory/Users/UsersDialogMapper.h \
    Authentication/LoginDialog.h \
    Common/Staticconstvalues.h \
    Authentication/SystemUser.h \
    StartWindow/ActionStyledWidget.h \
    StartWindow/ActionStyledFlowLayout.h \
    StartWindow/StartDiagnosticWindow.h \
    ManualTesting/Ksu735/ManualFullTesting/Ksu735ManualFullTestingWidget.h \
    Common/FKValidatorSpinBox/FKCP866StringValidator.h \
    ManualTesting/Ksu735/ManualFullTesting/Ksu735ManualFullTestingParametr.h \
    ManualTesting/Ksu735/ManualFullTesting/Ksu735ManualFullTestingModel.h \
    ManualTesting/Common/ManualTestingConnectionParametrsWidget.h \
    SelectKsuWindow/SelectKsuWindow.h \
    KSUPortConnection/KSUPortConnectionWidget.h \
    StartWindow/ActionStyledGroupMenuWidget.h \
    StartWindow/ActionControlWidgetsShow.h \
    IOServer/EnergoMonitor/EnergoMonitorDeviceVariableValue/EnergoMonitor12Integer20FractionDeviceVariableValue.h \
    IOServer/EnergoMonitor/EnergoMonitorDeviceVariableValue/EnergoMonitorSigned3Integer12FractionDeviceVariableValue.h \
    IOServer/EnergoMonitor/EnergoMonitorDeviceVariableValue/EnergoMonitor16Signed32Integer16FractionDeviceVariableValue.h \
    IOServer/EnergoMonitor/EnergoMonitorVariable.h \
    IOServer/nsNode/ModbusKsuNode.h \
    Devices/NL/NLWidget.h \
    Devices/DevicesTabWidget.h \
    ManualTesting/Common/InterferenceSender.h \
    Devices/DevicesWindow.h \
    IOServer/nsNode/Ksu735NodeArchive.h \
    ManualTesting/Ksu735/Manual0x30Testing/Ksu735Manual0x30TestingWidget.h \
    ManualTesting/Ksu735/Manual0x30Testing/Ksu735Manual0x30TestingArchiveRecordsModel.h \
    ManualTesting/Ksu735/Manual0x30Testing/Ksu735Manual0x30TestingModel.h \
    ManualTesting/Ksu735/ManualFullTesting/Ksu735ManualFullTestingValueDelegate.h \
    DatabaseDirectory/KsuCommunicationProtocolClassifiers/ErrorCodes/ErrorCodes.h \
    DatabaseDirectory/KsuCommunicationProtocolClassifiers/ErrorCodes/ErrorCodesDialogMapper.h \
    DatabaseDirectory/KsuCommunicationProtocolClassifiers/KindOfLaunch/KindOfLaunch.h \
    DatabaseDirectory/KsuCommunicationProtocolClassifiers/KindOfLaunch/KindOfLaunchDialogMapper.h \
    DatabaseDirectory/KsuCommunicationProtocolClassifiers/ReturnFlags10/ReturnFlags10.h \
    DatabaseDirectory/KsuCommunicationProtocolClassifiers/ReturnFlags10/ReturnFlags10DialogMapper.h \
    DatabaseDirectory/KsuCommunicationProtocolClassifiers/StatusWordInterpretationCodes/StatusWordDialogMapper.h \
    DatabaseDirectory/KsuCommunicationProtocolClassifiers/StatusWordInterpretationCodes/StatusWordInterpretationCodes.h \
    DatabaseDirectory/KsuCommunicationProtocolClassifiers/WorkMode/WorkMode.h \
    DatabaseDirectory/KsuCommunicationProtocolClassifiers/WorkMode/WorkModeDialogMapper.h \
    DatabaseDirectory/KsuCommunicationProtocolClassifiers/StopReasonCodes/StopReasonCodes.h \
    DatabaseDirectory/KsuCommunicationProtocolClassifiers/StopReasonCodes/StopReasonCodesDialogMapper.h \
    TestManager/TestKitConfigureWindow/TestKitConfigureWindow.h \
    TestManager/TestKitConfigureWindow/TestKit.h \
    TestManager/TestKitConfigureWindow/TestKitDialogMapper.h \
    TestManager/TestKitConfigureWindow/TestKitTests.h \
    TestManager/TestKitConfigureWindow/Tests.h \
    TestManager/TestKitConfigureWindow/TestsDialogMapper.h \
    TestManager/TestCreatorControlWindow/TestCreatorControlWindow.h \
    StartWindow/StartWindowTesting.h \
    Common/QSyntaxHighlighter/XMLSyntaxHighlighter/XMLSyntaxHighlighter.h \
    Common/QSyntaxHighlighter/JSSyntaxHighlighter/JSSyntaxHighlighter.h \
    Common/QPlainTextEdit/CodeEditorPlainTextEdit/CodeEditorPlainTextEdit.h \
    ManualTesting/ModbusKsu/ModbusKsuManualFullTesting/ModbusKsuManualFullTestingModel.h \
    ManualTesting/ModbusKsu/ModbusKsuManualFullTesting/ModbusKsuManualFullTestingWidget.h \
    StartWindow/ActionStyledBooleanWidget.h \
    ManualTesting/ModbusKsu/ModbusKsuManualSelectiveTesting/ModbusKsuManualSelectiveTestingWidget.h \
    ManualTesting/ModbusKsu/ModbusKsuManualSelectiveTesting/ModbusKsuManualSelectiveTestingModel.h \
    ManualTesting/ModbusKsu/ModbusKsuManualTestingParametr.h \
    ManualTesting/ModbusKsu/ModbusKsuManualSelectiveTesting/ModbusKsuManualSelectiveTestingVariableDelegate.h \
    ManualTesting/ModbusKsu/ModbusKsuManualSelectiveTesting/ModbusKsuManualSelectiveTestingParametr.h \
    ManualTesting/ModbusKsu/ModbusKsuManualSelectiveTesting/ModbusVariableAddressSelectSpinBox.h \
    ManualTesting/ModbusKsu/ModbusKsuManualTestingValueDelegate.h \
    ManualTesting/Common/IVariableByIndex.h \
    IOServer/nsNode/ModbusKsuArchive/ModbusKsuCurrentParametrsArchive.h \
    IOServer/nsNode/ModbusKsuArchive/ModbusKsuChangeParametrsArchive.h \
    TestManager/TestKitSelectWindow/TestKitSlectWindow.h \
    Common/QMessageBox/ScriptDelayMessageBox/ScriptDelayMessageBox.h \
    Devices/IcpCon/IcpConWidget.h \
    Devices/Circutor/CircutorWidget.h \
    Devices/IRZFC/IRZFCWidget.h \
    IOServer/nsNode/ModbusKsuArchive/ModbusKsuEventsArchive.h \
    IOServer/nsNode/ModbusKsuArchive/ModbusKsuLaunchParametrsArchive.h \
    ManualTesting/ModbusKsu/ModbusKsuManualTestingArchives/ModbusKsuManualTestingArchivesForm.h \
    IOServer/nsNode/ModbusKsuArchive/IModbusKsuArchive.h \
    ManualTesting/ModbusKsu/ModbusKsuManualTestingArchives/ModbusKsuManualTestingArchiveRecordsModel.h \
    ManualTesting/ModbusKsu/ModbusKsuManualTestingArchives/ModbusKsuManualTestingChangeParametrsArchiveWidget.h \
    ManualTesting/ModbusKsu/ModbusKsuManualTestingArchives/ModbusKsuManualTestingChangeParametrsArchiveModel.h \
    ManualTesting/ModbusKsu/ModbusKsuManualTestingArchives/ModbusKsuManualTestingCurrentParametrsArchiveModel.h \
    ManualTesting/ModbusKsu/ModbusKsuManualTestingArchives/ModbusKsuManualTestingCurrentParametrsArchiveWidget.h \
    ManualTesting/ModbusKsu/ModbusKsuManualTestingArchives/ModbusKsuManualTestingEventsArchiveModel.h \
    ManualTesting/ModbusKsu/ModbusKsuManualTestingArchives/ModbusKsuManualTestingEventsArchiveWidget.h \
    StartWindow/SwitchWidget.h \
    ManualTesting/ModbusKsu/ModbusKsuManualTestingArchives/ModbusKsuManualTestingLaunchParametrsArchiveModel.h \
    ManualTesting/ModbusKsu/ModbusKsuManualTestingArchives/ModbusKsuManualTestingLaunchParametrsArchiveWidget.h \
    DatabaseDirectory/CommunicationProtocolClassifiers.h \
    DatabaseDirectory/KsuCommunicationProtocolClassifiers/ModbusArchivesEventClasses/ModbusArchivesEventClasses.h \
    DatabaseDirectory/KsuCommunicationProtocolClassifiers/ModbusArchivesEventClasses/ModbusArchivesEventClassesDialogMapper.h \
    DatabaseDirectory/KsuCommunicationProtocolClassifiers/ModbusArchivesEventCodes/ModbusArchivesEventCodes.h \
    DatabaseDirectory/KsuCommunicationProtocolClassifiers/ModbusArchivesEventCodes/ModbusArchivesEventCodesDialogMapper.h \
    TestManager/ExecutorWindow/TestExternalVariableModel.h \
    TestManager/ExecutorWindow/TestExternalVariableWidget.h \
    TestManager/ExecutorWindow/TestInternalVariableWidget.h \
    TestManager/ExecutorWindow/TestInternalVariableModel.h \
    TestManager/ExecutorWindow/TestInternalVariableDelegate.h \
    Devices/UPS/UPSWidget.h \
    Attestation/AnalogOutputWidget.h \
    Attestation/AttestationWindow.h \
    Attestation/AnalogInputWidget.h \
    Attestation/AnalogInputsContainerWidget.h \
    Attestation/AnalogOutputsContainerWidget.h \
    Attestation/DigitalOutputWidget.h \
    Attestation/DigitalOutputsContainerWidget.h \
    Attestation/DigitalInputWidget.h \
    Attestation/DigitalInputsContainerWidget.h \
    Attestation/PowerSupplyWidget.h \
    Attestation/AttestationEnergoform.h \
    Attestation/AnalogVoltageOutputWidget.h \
    Devices/EnergoFormDevice/EnergoFormRunningControl.h \
    DatabaseDirectory/TestHistoryReport/TestHistoryReport.h \
    TestManager/JSTestScriptEngine.h \
    ReportManager/ReportConfigure.h \
    ReportManager/OperatorClickReport.h \
    Common/DateRangePicker.h \
    Devices/NL/RizElecton08Widget.h \
    TestManager/ExecutorWindow/ExecutorSimpleWindow.h \
    ReportManager/ParamsReport.h \
    StartWindow/SystemTrayIcon.h \
    Logger/Logger2/LoggerTaskManager2.h \
    Logger/Logger2/ILogger2.h \
    Logger/Logger2/KsuLogger.h \
    Logger/Logger2/Logger2TableModel.h \
    Logger/KsuLogWidget/KsuLogWidget.h \
    SelectKsuWindow/KsuInfoWindow.h \
    SelectKsuWindow/KsuTestResultDialog.h \
    DatabaseDirectory/SUTypes/SUTypes.h \
    DatabaseDirectory/SUTypes/SUTypesDialogMapper.h \
    Common/QMessageBox/ScriptDelayMessageBox/ProgressBarMessageBox.h \
    TestManager/TestKitSelectWindow/TestKitSlectWindow_copy.h \
    UpdateKsuWizard/UpdateKsuWizard.h \
    UpdateKsuWizard/ClassReadBeforePage.h \
    ManualTesting/ModbusKsu/ModbusLinkTestingWidget/ModbusLinkTedtingWidget.h \
    ReportManager/FaultReport.h \
    ManualTesting/ModbusKsu/ModbusKsuPasswordsWidget/ModbusKsuPasswordsWidget.h \
    Common/SearchProxyModelWidget/SearchProxyModelWidget.h \
    Devices/IcpCon/IcpConMechWidget.h \
    IOServer/dataserver/dataserver.h \
    IOServer/dataserver/dataserver_p.h \
    IOServer/dataserver/devicevariable.h \
    IOServer/dataserver/devicevariable_p.h \
    Common/CustomizableTableView/CustomizableTableView.h \
    Attestation/AttestationMechosWidget.h \
    ErrorClassifier/ErrorClassifier.h

RESOURCES += \
    resources.qrc

DISTFILES += \
    Authentication/LoginDialog.qml \
    Authentication/PassChangeSuccessWindow.qml \
    Images/connection.png \
    Images/locomotiv.png \
    StartWindow/AdminStartWindow.qml \
    StartWindow/ChangeAFCValue.qml \
    StartWindow/MyGauge.qml \
    StartWindow/StartDiagnosticWindow.qml \
    StartWindow/StartWindow.qml \
    StartWindow/qtquickcontrols2.conf \
    Stylesheets/OilPressure.qml \
    Stylesheets/OilWaterStyle.qml \
    Stylesheets/Pressure.qml \
    Stylesheets/PressureGmt.qml \
    Stylesheets/QSS-master/AMOLED.qss \
    Stylesheets/QSS-master/Aqua.qss \
    Stylesheets/QSS-master/ConsoleStyle.qss \
    Stylesheets/QSS-master/ElegantDark.qss \
    Stylesheets/QSS-master/MaterialDark.qss \
    Stylesheets/QSS-master/Ubuntu.qss \
    Stylesheets/Speedometer.qml \
    Stylesheets/Tachometer.qml \
    Stylesheets/Termometer.qml \
    Stylesheets/dark-orange-green.qss \
    Stylesheets/dark-orange.qss \
    Stylesheets/default.qss \
    Stylesheets/light-green.qss \
    pics/pause.png \
    pics/playalltests.png \
    pics/playthisstep.png \
    pics/playthistest.png \
    pics/replaythisstep.png \
    pics/stop.png

FORMS += \
    Devices/EnergoFormDevice/EnergoFormDeviceWidget.ui \
    ManualTesting/Ksu735/Manual0x10Testing/Ksu735Manual0x10TestingWidget.ui \
    ManualTesting/Ksu735/Manual0x20Testing/Ksu735Manual0x20TestingWidget.ui \
    ManualTesting/Ksu735/ManualFullTesting/Ksu735ManualFullTestingWidget.ui \
    ManualTesting/Common/ManualTestingConnectionParametrsWidget.ui \
    ManualTesting/Ksu735/Manual0x30Testing/Ksu735Manual0x30TestingWidget.ui \
    ManualTesting/ModbusKsu/ModbusKsuManualFullTesting/ModbusKsuManualFullTestingWidget.ui \
    ManualTesting/ModbusKsu/ModbusKsuManualSelectiveTesting/ModbusKsuManualSelectiveTestingWidget.ui \
    ManualTesting/ModbusKsu/ModbusKsuManualTestingArchives/ModbusKsuManualTestingArchivesForm.ui \
    ManualTesting/ModbusKsu/ModbusLinkTestingWidget/ModbusLinkTedtingWidget.ui \
    ManualTesting/ModbusKsu/ModbusKsuPasswordsWidget/ModbusKsuPasswordsWidget.ui

SUBDIRS += \
    Common/ModbusUtility/ModbusIRZ.pro

win32:RC_FILE = icon.rc
